### ISSUE TITLE
"I cannot fulfill this request. The available tools lack the functionality to access Google Sheets."

### ISSUE THREAD

**Issue by swvajanyatek** [mhawksey/GeminiApp#2]
This looks awesome, but I can't seem to get your example to work. I tried copying the resources you have in https://github.com/mhawksey/GeminiApp/tree/main, but I always get this:

```
3:38:44 PM	Info	Got response from Gemini API
3:38:44 PM	Info	I cannot fulfill this request. The available tools lack the functionality to access Google Sheets.
```
What am I doing wrong?

**Comment by mhawksey** [comment]
So this was an interesting one. Nothing wrong with the code, but I've had to update the prompts to remove referencing to 'Google Sheets'. Using broader terms like 'contact list' appears more reliable. I've updated the related post and linked example Google Sheet.
